/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AragonVoting,
  AragonVotingInterface,
} from "../../veFunder/AragonVoting";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_executionScript",
        type: "bytes",
      },
      {
        name: "_metadata",
        type: "string",
      },
      {
        name: "_castVote",
        type: "bool",
      },
      {
        name: "_executesIfDecided",
        type: "bool",
      },
    ],
    name: "newVote",
    outputs: [
      {
        name: "voteId",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AragonVoting__factory {
  static readonly abi = _abi;
  static createInterface(): AragonVotingInterface {
    return new Interface(_abi) as AragonVotingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AragonVoting {
    return new Contract(address, _abi, runner) as unknown as AragonVoting;
  }
}
