/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZapsUCrvV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimFromVaultAndStakeIn3PoolConvex"
      | "claimFromVaultAsCrv"
      | "claimFromVaultAsCvx"
      | "claimFromVaultAsEth"
      | "claimFromVaultAsUsdt"
      | "claimFromVaultViaUniV2EthPair"
      | "depositFromCrv"
      | "depositFromEth"
      | "depositFromUCrv"
      | "depositViaUniV2EthPair"
      | "setApprovals"
      | "vault"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimFromVaultAndStakeIn3PoolConvex",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsCrv",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsCvx",
    values: [BigNumberish, BigNumberish, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsEth",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsUsdt",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultViaUniV2EthPair",
    values: [BigNumberish, BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromCrv",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromEth",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromUCrv",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositViaUniV2EthPair",
    values: [BigNumberish, BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimFromVaultAndStakeIn3PoolConvex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsCvx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsUsdt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultViaUniV2EthPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromUCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositViaUniV2EthPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export interface ZapsUCrvV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ZapsUCrvV2;
  waitForDeployment(): Promise<this>;

  interface: ZapsUCrvV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimFromVaultAndStakeIn3PoolConvex: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  claimFromVaultAsCrv: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  claimFromVaultAsCvx: TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: AddressLike,
      lock: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  claimFromVaultAsEth: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  claimFromVaultAsUsdt: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  claimFromVaultViaUniV2EthPair: TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: AddressLike,
      outputToken: AddressLike,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  depositFromCrv: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  depositFromEth: TypedContractMethod<
    [minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "payable"
  >;

  depositFromUCrv: TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  depositViaUniV2EthPair: TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: AddressLike,
      inputToken: AddressLike,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovals: TypedContractMethod<[], [void], "nonpayable">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimFromVaultAndStakeIn3PoolConvex"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFromVaultAsCrv"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFromVaultAsCvx"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: AddressLike,
      lock: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFromVaultAsEth"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFromVaultAsUsdt"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimFromVaultViaUniV2EthPair"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: AddressLike,
      outputToken: AddressLike,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositFromCrv"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositFromEth"
  ): TypedContractMethod<
    [minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositFromUCrv"
  ): TypedContractMethod<
    [amount: BigNumberish, minAmountOut: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositViaUniV2EthPair"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: AddressLike,
      inputToken: AddressLike,
      to: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovals"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
